[theme
]
primaryColor="#HEXADECIMAL_COLOR"
backgroundColor="#HEXADECIMAL_COLOR"
secondaryBackgroundColor="#HEXADECIMAL_COLOR"
textColor="#HEXADECIMAL_COLOR"
font="sans serif"



[browser
]


serverAddress = "localhost"

gatherUsageStats = true


serverPort = 8501
